f = open('frontend/src/pages/VendasPage.js', 'r', encoding='utf-8')
content = f.read()
f.close()

old = '        {searchTerm && (\n          <p className="text-xs text-[#705A4D] mt-1">Encontrados: {filteredVendas.length} de {vendas.length} vendas</p>\n        )}\n      </div>'

new = '        <p className="text-xs text-[#705A4D] mt-1">Encontrados: {filteredVendas.length} de {vendas.length} vendas</p>\n      </div>\n      <div className="flex flex-wrap gap-2 mt-3">\n        <select value={filtroStatus} onChange={e => setFiltroStatus(e.target.value)} className="px-3 py-1.5 text-sm border border-[#8B5A3C]/30 rounded-lg bg-[#FFFDF8] text-[#3E2723] outline-none">\n          <option value="todos">Todos os status</option>\n          <option value="pago">Pago</option>\n          <option value="pendente">A Receber</option>\n          <option value="cancelada">Cancelada</option>\n        </select>\n        <select value={filtroTipo} onChange={e => setFiltroTipo(e.target.value)} className="px-3 py-1.5 text-sm border border-[#8B5A3C]/30 rounded-lg bg-[#FFFDF8] text-[#3E2723] outline-none">\n          <option value="todos">Todos os tipos</option>\n          <option value="pedido">Pedido</option>\n          <option value="direta">Venda Direta</option>\n        </select>\n        <select value={filtroPeriodo} onChange={e => setFiltroPeriodo(e.target.value)} className="px-3 py-1.5 text-sm border border-[#8B5A3C]/30 rounded-lg bg-[#FFFDF8] text-[#3E2723] outline-none">\n          <option value="todos">Todo o periodo</option>\n          <option value="hoje">Hoje</option>\n          <option value="semana">Esta semana</option>\n          <option value="mes">Este mes</option>\n        </select>\n        <select value={filtroClienteId} onChange={e => setFiltroClienteId(e.target.value)} className="px-3 py-1.5 text-sm border border-[#8B5A3C]/30 rounded-lg bg-[#FFFDF8] text-[#3E2723] outline-none">\n          <option value="">Todos os clientes</option>\n          {clientes.map(c => <option key={c.id} value={c.id}>{c.nome}</option>)}\n        </select>\n        {(filtroStatus !== "todos" || filtroTipo !== "todos" || filtroPeriodo !== "todos" || filtroClienteId) && (\n          <button onClick={() => { setFiltroStatus("todos"); setFiltroTipo("todos"); setFiltroPeriodo("todos"); setFiltroClienteId(""); }} className="px-3 py-1.5 text-sm text-red-600 border border-red-300 rounded-lg hover:bg-red-50">X Limpar filtros</button>\n        )}\n      </div>'

result = content.replace(old, new, 1)
open('frontend/src/pages/VendasPage.js', 'w', encoding='utf-8').write(result)
print("Done" if result != content else "NOT FOUND")
