f = open('frontend/src/pages/RelatoriosPage.js', 'r', encoding='utf-8')
content = f.read()
f.close()

new_tab = (
    "\n      {/* TAB: CONSISTENCIA */}\n"
    "      {activeTab === 'consistencia' && (\n"
    "        <div className=\"space-y-6\">\n"
    "          <div className=\"bg-[#FFFDF8] border border-[#8B5A3C]/15 rounded-xl p-6 shadow-sm\">\n"
    "            <h3 className=\"text-xl font-serif font-semibold text-[#3E2723] mb-4\">Pedidos Concluidos sem Venda</h3>\n"
    "            {pedidosSemVenda === null ? (\n"
    "              <p className=\"text-[#705A4D]\">Carregando...</p>\n"
    "            ) : pedidosSemVenda.length === 0 ? (\n"
    "              <p className=\"text-green-600 font-medium\">Todos os pedidos tem venda registrada!</p>\n"
    "            ) : (\n"
    "              <table className=\"w-full\">\n"
    "                <thead className=\"bg-[#E8D5C4]\"><tr>\n"
    "                  <th className=\"text-left px-4 py-2 text-sm font-semibold text-[#3E2723]\">Pedido</th>\n"
    "                  <th className=\"text-left px-4 py-2 text-sm font-semibold text-[#3E2723]\">Cliente</th>\n"
    "                  <th className=\"text-right px-4 py-2 text-sm font-semibold text-[#3E2723]\">Valor</th>\n"
    "                </tr></thead>\n"
    "                <tbody>{pedidosSemVenda.map((p, i) => (\n"
    "                  <tr key={i} className=\"border-t border-[#8B5A3C]/10 hover:bg-[#F5E6D3]/50\">\n"
    "                    <td className=\"px-4 py-3 text-sm font-medium text-[#3E2723]\">{p.numero}</td>\n"
    "                    <td className=\"px-4 py-3 text-sm text-[#705A4D]\">{p.cliente_nome}</td>\n"
    "                    <td className=\"px-4 py-3 text-sm text-right font-bold\">{formatCurrency(p.valor_total)}</td>\n"
    "                  </tr>\n"
    "                ))}</tbody>\n"
    "              </table>\n"
    "            )}\n"
    "          </div>\n"
    "          <div className=\"bg-[#FFFDF8] border border-[#8B5A3C]/15 rounded-xl p-6 shadow-sm\">\n"
    "            <h3 className=\"text-xl font-serif font-semibold text-[#3E2723] mb-4\">Possiveis Duplicatas</h3>\n"
    "            {duplicatas === null ? (\n"
    "              <p className=\"text-[#705A4D]\">Carregando...</p>\n"
    "            ) : duplicatas.length === 0 ? (\n"
    "              <p className=\"text-green-600 font-medium\">Nenhuma duplicata encontrada!</p>\n"
    "            ) : (\n"
    "              <table className=\"w-full\">\n"
    "                <thead className=\"bg-[#E8D5C4]\"><tr>\n"
    "                  <th className=\"text-left px-4 py-2 text-sm font-semibold text-[#3E2723]\">Cliente</th>\n"
    "                  <th className=\"text-left px-4 py-2 text-sm font-semibold text-[#3E2723]\">Pedido</th>\n"
    "                  <th className=\"text-center px-4 py-2 text-sm font-semibold text-[#3E2723]\">Produtos em Comum</th>\n"
    "                </tr></thead>\n"
    "                <tbody>{duplicatas.map((d, i) => (\n"
    "                  <tr key={i} className=\"border-t border-[#8B5A3C]/10 hover:bg-[#F5E6D3]/50\">\n"
    "                    <td className=\"px-4 py-3 text-sm font-medium text-[#3E2723]\">{d.cliente_nome}</td>\n"
    "                    <td className=\"px-4 py-3 text-sm text-[#705A4D]\">{d.pedido_numero}</td>\n"
    "                    <td className=\"px-4 py-3 text-sm text-center\"><span className=\"px-2 py-1 bg-orange-100 text-orange-700 rounded text-xs font-bold\">{d.produtos_em_comum}</span></td>\n"
    "                  </tr>\n"
    "                ))}</tbody>\n"
    "              </table>\n"
    "            )}\n"
    "          </div>\n"
    "        </div>\n"
    "      )}\n"
)

idx = content.rfind("    </div>\n  );\n}")
content = content[:idx] + new_tab + "    </div>\n  );\n}"
open('frontend/src/pages/RelatoriosPage.js', 'w', encoding='utf-8').write(content)
print("Done" if 'consistencia' in content else "NOT FOUND")